version: "3.8"
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cdn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: cdn_db

  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - incident_report/.env
    depends_on:
      - db
    volumes:
      - .:/app
    container_name: cdn_backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
