version: "3.8"
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=cdn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: cdn_db

  redis:
    image: redis:6
    ports:
      - 6379:6379
    container_name: cdn_redis
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - incident_report/.env
    depends_on:
      - db
    volumes:
      - .:/app
    container_name: cdn_backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    command: celery -A incident_report worker -l info
    container_name: cdn_celery
    volumes:
      - .:/app
    env_file:
      - incident_report/.env
    depends_on:
      - db
      - redis
      - backend

  celery-beat:
    build: .
    command: celery -A incident_report beat -l info
    container_name: cdn_celery_beat
    volumes:
      - .:/app
    env_file:
      - incident_report/.env
    depends_on:
      - db
      - redis
      - backend

volumes:
  postgres_data:
