# Generated by Django 3.2.12 on 2022-03-08 19:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='URL of monitoring system', unique=True, verbose_name='URL')),
                ('title', models.CharField(help_text='Title of monitoring system', max_length=150, verbose_name='Title')),
                ('start_page', models.IntegerField(default=0, help_text='First page of the URL', verbose_name='Start')),
                ('current_page', models.IntegerField(default=0, editable=False, help_text='Current page of the URL', verbose_name='Start')),
                ('last_status', models.IntegerField(blank=True, editable=False, help_text='Status code of last request', null=True)),
                ('last_update', models.DateTimeField(blank=True, editable=False, help_text='Last time pull the incident reports', null=True)),
                ('is_active', models.BooleanField(default=True, editable=False, help_text='A monitoring system will become inactive when a permanent error occurs')),
            ],
            options={
                'verbose_name': 'Monitoring system',
                'verbose_name_plural': 'Monitoring systems',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('incident', models.CharField(max_length=250, verbose_name='Incident')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('report_type', models.IntegerField(help_text='Admin created OR system pulled', verbose_name='report type')),
                ('monitoring_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report.monitoringsystem', verbose_name='Monitoring system')),
            ],
            options={
                'verbose_name': 'Incident report',
                'verbose_name_plural': 'Incident reports',
            },
        ),
    ]
